version: "3.8"
services:
  redis:
    image: redis:alpine
    restart: always
      
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"


  worker:
    build: ./worker
    depends_on:
      - db
      - redis

  vote:
    build: ./vote
    ports:
      - "80:80"
    depends_on:
      - redis
  
  result:
    build: ./result
    ports:
      - "81:80"
    depends_on:
      - db
